config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find_by(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Sarah Builds Stuff
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #sidebar
      %ul
        %li.category Website
        %li= link_to "Blog", root_path
        %li About
      %ul
        %li.category Social
        %li
          %a{:href => "https://twitter.com/sarahdashdashp"} Twitter
        %li
          %a{:href => "http://instagram.com/sarahdashdashp"} Instagram
        %li
          %a{:href => "https://github.com/sarahjschultz"} Github
        %li
          %a{:href => "mailto:sarahjschultz@gmail.com"} Email
      %p.sign_in Admin Login
    #main_content
      #header
        - if current_page?(root_path)
          %p All Posts
        - else
          = link_to "Back to All Posts", root_path
        .buttons
          %button.button= link_to "New Post", new_post_path
          %button.button Log Out
      - flash.each do |name, msg|
        = content_tag(:div, msg, class: "alert")
      = yield

app/views/posts/_form.html.haml
= form_for :post, url: posts_path do |f|
  -if @post.errors.any?
    #errors
      %h2
        = pluralize(@post.errors.count, "error")
        prevented this post from saving:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  = f.label :title
  = f.text_field :title
  %br
  %br
  = f.label :body
  = f.text_field :body
  %br
  %br
  = f.submit

app/views/posts/index.html.haml
- @posts.each do |post|
  .post_wrapper
    %h2.title= link_to post.title
    %p.date= post.created_at.strftime("%B %d, %Y")

app/views/posts/new.html.haml
#page_wrapper
  %h1 New Post
  = render 'form'

app/views/posts/show.html.haml
#post_content
  %h1.title=@post.title
  %p.date
    Submitted #{time_ago_in_words(@post.created_at)} ago
  %p.body=@post.body